@extends('layouts.dash')
@section('title', 'Institutional Trading Signals')

@section('content')
<div class="container-fluid py-3">
    <!-- Header Banner -->
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
        <div>
            <div class="d-flex align-items-center gap-2 mb-1">
                <span class="badge bg-warning bg-opacity-10 text-warning border border-warning border-opacity-25 px-2 py-1 rounded-pill f-11 f-w-700">
                    <i class="fa-solid fa-bolt me-1"></i> INSTITUTIONAL SIGNALS DESK
                </span>
                @if($isLocked)
                    <span class="badge bg-warning bg-opacity-10 text-warning border border-warning border-opacity-25 px-2 py-1 rounded-pill f-11 f-w-700">
                        <i class="fa-solid fa-lock me-1"></i> Clearance Required
                    </span>
                @endif
            </div>
            <h4 class="f-w-800 text-dark mb-1">Premium Trading Signals</h4>
            <p class="text-muted f-13 mb-0">High-conviction, audited market setups generated by our senior quantitative analysts and proprietary algorithms.</p>
        </div>

        <div class="d-flex flex-wrap align-items-center gap-2">
            <a href="{{ route('demotrading') }}" class="btn btn-outline-secondary rounded-pill px-3 py-2 f-13 f-w-600">
                <i class="fa-solid fa-graduation-cap me-1"></i> Test in Demo
            </a>
            <button type="button" class="btn btn-primary rounded-pill px-3 py-2 f-13 f-w-700 shadow-sm" onclick="refreshSignals()">
                <i class="fa-solid fa-rotate me-1" id="sigRefreshIcon"></i> Refresh Signals
            </button>
        </div>
    </div>

    @if($isLocked)
    <!-- Institutional Clearance Banner -->
    <div class="card border-0 mb-4 text-white p-3 shadow-sm" style="background: linear-gradient(135deg, #1e1b4b 0%, #312e81 50%, #4338ca 100%); border-radius: 14px;">
        <div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3">
            <div class="d-flex align-items-center gap-3">
                <div class="rounded-circle bg-warning bg-opacity-20 d-flex align-items-center justify-content-center text-warning flex-shrink-0" style="width: 44px; height: 44px; font-size: 20px;">
                    <i class="fa-solid fa-shield-halved"></i>
                </div>
                <div>
                    <h6 class="text-white f-w-700 mb-1 f-14">Institutional Signal Execution: <span class="text-warning">Locked</span></h6>
                    <p class="text-white text-opacity-80 f-12 mb-0">
                        One-click signal execution on live exchange liquidity requires qualified capital of <strong>{{ $settings->currency }}{{ number_format($settings->min_trading_balance, 2) }}</strong>. Your qualified balance is <strong>{{ $settings->currency }}{{ number_format($userTotalBalance, 2) }}</strong>.
                    </p>
                </div>
            </div>
            <div class="d-flex gap-2 flex-shrink-0">
                <button type="button" class="btn btn-warning text-dark rounded-pill px-3 py-2 f-12 f-w-700" onclick="window.openTradingClearanceModal(event, 'Premium Signals')">
                    <i class="fa-solid fa-unlock me-1"></i> Request Clearance
                </button>
                <a href="{{ route('deposits') }}" class="btn btn-outline-light rounded-pill px-3 py-2 f-12 f-w-600">
                    <i class="fa-solid fa-wallet me-1"></i> Deposit
                </a>
            </div>
        </div>
    </div>
    @endif

    <!-- Signals Track Record Ribbon -->
    <div class="row g-3 mb-4">
        <div class="col-6 col-md-3">
            <div class="card border shadow-sm h-100 p-3 mb-0" style="border-radius: 12px;">
                <small class="text-muted f-11 d-block mb-1">Success Win Rate</small>
                <h5 class="f-w-800 text-success mb-0 f-18">94.8%</h5>
                <small class="text-muted f-10">Last 180 signals audited</small>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="card border shadow-sm h-100 p-3 mb-0" style="border-radius: 12px;">
                <small class="text-muted f-11 d-block mb-1">Average Risk-to-Reward</small>
                <h5 class="f-w-800 text-primary mb-0 f-18">1 : 3.4</h5>
                <small class="text-success f-10"><i class="fa-solid fa-shield-check me-1"></i>Asymmetric payoff</small>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="card border shadow-sm h-100 p-3 mb-0" style="border-radius: 12px;">
                <small class="text-muted f-11 d-block mb-1">Monthly Pips / Points</small>
                <h5 class="f-w-800 text-dark mb-0 f-18">+4,820 Pips</h5>
                <small class="text-success f-10"><i class="fa-solid fa-arrow-trend-up me-1"></i>+18.4% gain</small>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="card border shadow-sm h-100 p-3 mb-0" style="border-radius: 12px;">
                <small class="text-muted f-11 d-block mb-1">Active Setups Today</small>
                <h5 class="f-w-800 text-warning mb-0 f-18">5 Setups</h5>
                <small class="text-muted f-10">2 Target Hits • 3 Running</small>
            </div>
        </div>
    </div>

    <!-- Filter Buttons -->
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-primary active py-2 px-3 f-12" onclick="filterSignals('all', this)">All Signals</button>
            <button type="button" class="btn btn-outline-primary py-2 px-3 f-12" onclick="filterSignals('crypto', this)">Crypto Signals</button>
            <button type="button" class="btn btn-outline-primary py-2 px-3 f-12" onclick="filterSignals('forex', this)">Forex Signals</button>
            <button type="button" class="btn btn-outline-primary py-2 px-3 f-12" onclick="filterSignals('commodities', this)">Commodities</button>
        </div>
        <span class="text-muted f-12"><i class="fa-regular fa-clock me-1"></i> Feeds updated every 60s</span>
    </div>

    <!-- Signals Cards Grid -->
    <div class="row g-4 mb-4">
        <!-- Signal 1: BTC/USDT -->
        <div class="col-md-6 col-lg-4 sig-item" data-cat="crypto">
            <div class="card border shadow-sm h-100 mb-0" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center gap-2">
                            <i class="fa-brands fa-bitcoin text-warning f-24"></i>
                            <div>
                                <h6 class="f-w-800 text-dark mb-0 f-15">BTC / USDT</h6>
                                <small class="text-muted f-11">Spot & Perp • 25m ago</small>
                            </div>
                        </div>
                        <span class="badge bg-success py-1 px-2 rounded-pill f-11 f-w-700">
                            <i class="fa-solid fa-arrow-up me-1"></i> BUY / LONG
                        </span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted f-11">Confidence Score:</span>
                        <span class="badge bg-success bg-opacity-10 text-success rounded-pill f-11 f-w-700">98% High Conviction</span>
                    </div>

                    <div class="p-3 bg-light rounded-3 mb-3">
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Entry Range:</span>
                            <strong class="text-dark">$109,200.00 – $109,800.00</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 1 (TP1):</span>
                            <span class="text-success f-w-700">$112,500.00 <span class="badge bg-success rounded-pill f-9 ms-1">HIT</span></span>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 2 (TP2):</span>
                            <span class="text-dark f-w-600">$115,000.00</span>
                        </div>
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Target 3 (TP3):</span>
                            <span class="text-dark f-w-600">$118,500.00</span>
                        </div>
                        <div class="d-flex justify-content-between pt-2 border-top f-12">
                            <span class="text-danger f-w-600">Stop Loss (SL):</span>
                            <span class="text-danger f-w-700">$107,400.00</span>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary w-100 py-2 rounded-pill f-13 f-w-700 shadow-sm"
                            onclick="{{ $isLocked ? "window.openTradingClearanceModal(event, 'BTC Signal Execution')" : "executeSignal('BTC / USDT', 'BUY', 109500)" }}">
                        @if($isLocked)<i class="fa-solid fa-lock me-1"></i>@endif Execute Signal
                    </button>
                </div>
            </div>
        </div>

        <!-- Signal 2: ETH/USDT -->
        <div class="col-md-6 col-lg-4 sig-item" data-cat="crypto">
            <div class="card border shadow-sm h-100 mb-0" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center gap-2">
                            <i class="fa-brands fa-ethereum text-primary f-24"></i>
                            <div>
                                <h6 class="f-w-800 text-dark mb-0 f-15">ETH / USDT</h6>
                                <small class="text-muted f-11">Spot & Perp • 1h ago</small>
                            </div>
                        </div>
                        <span class="badge bg-success py-1 px-2 rounded-pill f-11 f-w-700">
                            <i class="fa-solid fa-arrow-up me-1"></i> BUY / LONG
                        </span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted f-11">Confidence Score:</span>
                        <span class="badge bg-success bg-opacity-10 text-success rounded-pill f-11 f-w-700">95% High Conviction</span>
                    </div>

                    <div class="p-3 bg-light rounded-3 mb-3">
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Entry Range:</span>
                            <strong class="text-dark">$3,380.00 – $3,410.00</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 1 (TP1):</span>
                            <span class="text-dark f-w-600">$3,520.00</span>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 2 (TP2):</span>
                            <span class="text-dark f-w-600">$3,680.00</span>
                        </div>
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Target 3 (TP3):</span>
                            <span class="text-dark f-w-600">$3,850.00</span>
                        </div>
                        <div class="d-flex justify-content-between pt-2 border-top f-12">
                            <span class="text-danger f-w-600">Stop Loss (SL):</span>
                            <span class="text-danger f-w-700">$3,290.00</span>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary w-100 py-2 rounded-pill f-13 f-w-700 shadow-sm"
                            onclick="{{ $isLocked ? "window.openTradingClearanceModal(event, 'ETH Signal Execution')" : "executeSignal('ETH / USDT', 'BUY', 3400)" }}">
                        @if($isLocked)<i class="fa-solid fa-lock me-1"></i>@endif Execute Signal
                    </button>
                </div>
            </div>
        </div>

        <!-- Signal 3: EUR/USD -->
        <div class="col-md-6 col-lg-4 sig-item" data-cat="forex">
            <div class="card border shadow-sm h-100 mb-0" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center gap-2">
                            <div class="rounded-circle bg-primary text-white d-flex align-items-center justify-content-center" style="width: 32px; height: 32px; font-size: 14px;">
                                <i class="fa-solid fa-euro-sign"></i>
                            </div>
                            <div>
                                <h6 class="f-w-800 text-dark mb-0 f-15">EUR / USD</h6>
                                <small class="text-muted f-11">Forex Major • 2h ago</small>
                            </div>
                        </div>
                        <span class="badge bg-danger py-1 px-2 rounded-pill f-11 f-w-700">
                            <i class="fa-solid fa-arrow-down me-1"></i> SELL / SHORT
                        </span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted f-11">Confidence Score:</span>
                        <span class="badge bg-primary bg-opacity-10 text-primary rounded-pill f-11 f-w-700">92% Conviction</span>
                    </div>

                    <div class="p-3 bg-light rounded-3 mb-3">
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Entry Range:</span>
                            <strong class="text-dark">1.0880 – 1.0890</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 1 (TP1):</span>
                            <span class="text-dark f-w-600">1.0820 (+65 pips)</span>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 2 (TP2):</span>
                            <span class="text-dark f-w-600">1.0775 (+110 pips)</span>
                        </div>
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Target 3 (TP3):</span>
                            <span class="text-dark f-w-600">1.0710 (+175 pips)</span>
                        </div>
                        <div class="d-flex justify-content-between pt-2 border-top f-12">
                            <span class="text-danger f-w-600">Stop Loss (SL):</span>
                            <span class="text-danger f-w-700">1.0925</span>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary w-100 py-2 rounded-pill f-13 f-w-700 shadow-sm"
                            onclick="{{ $isLocked ? "window.openTradingClearanceModal(event, 'EUR/USD Signal Execution')" : "executeSignal('EUR / USD', 'SELL', 1.0885)" }}">
                        @if($isLocked)<i class="fa-solid fa-lock me-1"></i>@endif Execute Signal
                    </button>
                </div>
            </div>
        </div>

        <!-- Signal 4: SOL/USDT -->
        <div class="col-md-6 col-lg-4 sig-item" data-cat="crypto">
            <div class="card border shadow-sm h-100 mb-0" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center gap-2">
                            <div class="rounded-circle bg-purple text-white d-flex align-items-center justify-content-center" style="width: 32px; height: 32px; font-size: 14px; background: #8b5cf6;">
                                <i class="fa-solid fa-bolt"></i>
                            </div>
                            <div>
                                <h6 class="f-w-800 text-dark mb-0 f-15">SOL / USDT</h6>
                                <small class="text-muted f-11">Spot & Perp • 4h ago</small>
                            </div>
                        </div>
                        <span class="badge bg-success py-1 px-2 rounded-pill f-11 f-w-700">
                            <i class="fa-solid fa-arrow-up me-1"></i> BUY / LONG
                        </span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted f-11">Confidence Score:</span>
                        <span class="badge bg-success bg-opacity-10 text-success rounded-pill f-11 f-w-700">96% High Conviction</span>
                    </div>

                    <div class="p-3 bg-light rounded-3 mb-3">
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Entry Range:</span>
                            <strong class="text-dark">$174.50 – $176.00</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 1 (TP1):</span>
                            <span class="text-success f-w-700">$182.00 <span class="badge bg-success rounded-pill f-9 ms-1">HIT (+4.3%)</span></span>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 2 (TP2):</span>
                            <span class="text-dark f-w-600">$194.00</span>
                        </div>
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Target 3 (TP3):</span>
                            <span class="text-dark f-w-600">$210.00</span>
                        </div>
                        <div class="d-flex justify-content-between pt-2 border-top f-12">
                            <span class="text-danger f-w-600">Stop Loss (SL):</span>
                            <span class="text-danger f-w-700">$169.00</span>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary w-100 py-2 rounded-pill f-13 f-w-700 shadow-sm"
                            onclick="{{ $isLocked ? "window.openTradingClearanceModal(event, 'SOL Signal Execution')" : "executeSignal('SOL / USDT', 'BUY', 175)" }}">
                        @if($isLocked)<i class="fa-solid fa-lock me-1"></i>@endif Execute Signal
                    </button>
                </div>
            </div>
        </div>

        <!-- Signal 5: Gold Spot -->
        <div class="col-md-6 col-lg-4 sig-item" data-cat="commodities">
            <div class="card border shadow-sm h-100 mb-0" style="border-radius: 16px;">
                <div class="card-body p-4">
                    <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="d-flex align-items-center gap-2">
                            <div class="rounded-circle bg-warning text-dark d-flex align-items-center justify-content-center" style="width: 32px; height: 32px; font-size: 14px; background: #fbbf24;">
                                <i class="fa-solid fa-ring"></i>
                            </div>
                            <div>
                                <h6 class="f-w-800 text-dark mb-0 f-15">XAU / USD (Gold)</h6>
                                <small class="text-muted f-11">Commodities • 6h ago</small>
                            </div>
                        </div>
                        <span class="badge bg-success py-1 px-2 rounded-pill f-11 f-w-700">
                            <i class="fa-solid fa-arrow-up me-1"></i> BUY / LONG
                        </span>
                    </div>

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted f-11">Confidence Score:</span>
                        <span class="badge bg-success bg-opacity-10 text-success rounded-pill f-11 f-w-700">97% High Conviction</span>
                    </div>

                    <div class="p-3 bg-light rounded-3 mb-3">
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Entry Price:</span>
                            <strong class="text-dark">$2,720.00</strong>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 1 (TP1):</span>
                            <span class="text-success f-w-700">$2,740.00 <span class="badge bg-success rounded-pill f-9 ms-1">HIT</span></span>
                        </div>
                        <div class="d-flex justify-content-between mb-1 f-12">
                            <span class="text-muted">Target 2 (TP2):</span>
                            <span class="text-success f-w-700">$2,755.00 <span class="badge bg-success rounded-pill f-9 ms-1">HIT (+350 pips)</span></span>
                        </div>
                        <div class="d-flex justify-content-between mb-2 f-12">
                            <span class="text-muted">Target 3 (TP3):</span>
                            <span class="text-dark f-w-600">$2,780.00</span>
                        </div>
                        <div class="d-flex justify-content-between pt-2 border-top f-12">
                            <span class="text-danger f-w-600">Stop Loss (SL):</span>
                            <span class="text-danger f-w-700">$2,705.00</span>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary w-100 py-2 rounded-pill f-13 f-w-700 shadow-sm"
                            onclick="{{ $isLocked ? "window.openTradingClearanceModal(event, 'Gold Signal Execution')" : "executeSignal('XAU / USD', 'BUY', 2748)" }}">
                        @if($isLocked)<i class="fa-solid fa-lock me-1"></i>@endif Execute Signal
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Push Notification Subscription Banner -->
    <div class="card border-0 mb-4 text-white p-4 shadow-sm" style="background: linear-gradient(135deg, #0ea5e9 0%, #2563eb 100%); border-radius: 16px;">
        <div class="d-flex flex-column flex-md-row align-items-md-center justify-content-between gap-3">
            <div class="d-flex align-items-center gap-3">
                <div class="rounded-circle bg-white bg-opacity-20 d-flex align-items-center justify-content-center text-white flex-shrink-0" style="width: 48px; height: 48px; font-size: 22px;">
                    <i class="fa-brands fa-telegram"></i>
                </div>
                <div>
                    <h5 class="text-white f-w-800 mb-1 f-16">Instant VIP Telegram & Mobile Signal Alerts</h5>
                    <p class="text-white text-opacity-90 f-12 mb-0">Never miss a breakout. Receive immediate push notifications with entry, stop loss, and take-profit targets right to your smartphone.</p>
                </div>
            </div>
            <a href="https://telegram.org" target="_blank" class="btn btn-light text-primary rounded-pill px-4 py-2 f-13 f-w-700 flex-shrink-0 shadow-sm">
                <i class="fa-brands fa-telegram me-1"></i> Connect VIP Channel
            </a>
        </div>
    </div>
</div>

<script>
    function filterSignals(cat, btn) {
        var buttons = btn.parentElement.querySelectorAll('button');
        buttons.forEach(b => b.classList.remove('active'));
        btn.classList.add('active');

        var items = document.querySelectorAll('.sig-item');
        items.forEach(it => {
            if (cat === 'all' || it.getAttribute('data-cat') === cat) {
                it.style.display = '';
            } else {
                it.style.display = 'none';
            }
        });
    }

    function refreshSignals() {
        var icon = document.getElementById('sigRefreshIcon');
        icon.classList.add('fa-spin');
        setTimeout(() => {
            icon.classList.remove('fa-spin');
            if (window.toastr) toastr.success('Signal desk synchronized. All confidence scores up to date.');
        }, 600);
    }

    function executeSignal(pair, side, price) {
        if (window.toastr) {
            toastr.success(`Parameters for ${pair} (${side} @ $${price}) populated. Routing to live execution book.`);
        } else {
            alert(`Signal for ${pair} executed!`);
        }
    }
</script>
@endsection
